// Code generated by "stringer -type=ColorCode"; DO NOT EDIT.

package colorcode

import "fmt"

const _ColorCode_name = "NoColorRedGreenYellowBlueMagentaCyan"

var _ColorCode_index = [...]uint8{0, 7, 10, 15, 21, 25, 32, 36}

func (i ColorCode) String() string {
	if i >= ColorCode(len(_ColorCode_index)-1) {
		return fmt.Sprintf("ColorCode(%d)", i)
	}
	return _ColorCode_name[_ColorCode_index[i]:_ColorCode_index[i+1]]
}
